m = 2; 
k = 8; 
x0 = 0.1; 
v0 = 10; 
omega_n = sqrt(k/m); 
t = linspace(0, 10, 1000); 
c = 0; 
zeta = c / (2 * sqrt(k * m)); 
x_undamped = x0 * cos(omega_n * t) + (v0 / omega_n) * sin(omega_n * t);
c = 1; 
zeta = c / (2 * sqrt(k * m)); 
omega_d = omega_n * sqrt(1 - zeta^2);
x_underdamped = exp(-zeta * omega_n * t) .* ...
    (x0 * cos(omega_d * t) + (v0 + zeta * omega_n * x0) / omega_d * sin(omega_d * t));
c = 8; 
zeta = 1; 
A = x0; 
B = v0 + omega_n * x0; 
x_critically_damped = (A + B * t) .* exp(-omega_n * t);
c = 20; 
zeta = c / (2 * sqrt(k * m)); 
r1 = -omega_n * (zeta + sqrt(zeta^2 - 1));
r2 = -omega_n * (zeta - sqrt(zeta^2 - 1));
C1 = (v0 - r2 * x0) / (r1 - r2);
C2 = x0 - C1;
x_overdamped = C1 * exp(r1 * t) + C2 * exp(r2 * t);
figure;
hold on;
plot(t, x_undamped, 'm-', 'LineWidth', 3); 
plot(t, x_underdamped, 'g--', 'LineWidth', 1); 
plot(t, x_critically_damped, 'b-.', 'LineWidth', 2.5); 
plot(t, x_overdamped, 'k:', 'LineWidth', 1.5); 
title('Time Response of Mass-Spring-Damper System');
xlabel('Time (s)');
ylabel('Displacement (m)');
legend('Undamped', 'Underdamped', 'Critically Damped', 'Overdamped');
grid off;
hold off;